In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv('~/mission_sih/mission_sih/data/land_use_data.csv')

In [4]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 17650701 entries, 0 to 17650700
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   year       int64
 1   land_type  str
 2   latitude   float64
 3   longitude  float64
dtypes: float64(2), int64(1), str(1)
memory usage: 538.7 MB

In [5]:
df2 = pd.read_csv("~/mission_sih/mission_sih/data/nasa_data_cleaned.csv")

In [6]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5089539 entries, 0 to 5089538
Data columns (total 12 columns):
 #   Column      Dtype
---  ------      -----
 0   latitude    float64
 1   longitude   float64
 2   brightness  float64
 3   scan        float64
 4   track       float64
 5   acq_date    str
 6   acq_time    int64
 7   confidence  int64
 8   bright_t31  float64
 9   frp         float64
 10  daynight    int64
 11  type        int64
dtypes: float64(7), int64(4), str(1)
memory usage: 466.0 MB

In [7]:
df1.head(3)

   year    land_type   latitude  longitude
0  2018  Agriculture  37.072196  74.712681
1  2018  Agriculture  37.062195  74.682680
2  2018  Agriculture  37.052194  74.682680

In [8]:
df2.head(3)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,confidence,bright_t31,frp,daynight,type
0,23.04102,92.52061,336.69,0.62,0.71,2018-04-01,606,1,296.72,6.39,0,0
1,22.58705,92.50738,329.40,0.63,0.72,2018-04-01,606,1,299.01,7.35,0,0
2,22.58846,92.51312,337.59,0.63,0.72,2018-04-01,606,1,299.01,6.89,0,0

,latitude,longitude,brightness,scan,track,acq_date,acq_time,confidence,bright_t31,frp,daynight,type
0,23.04102,92.52061,336.69,0.62,0.71,2018-04-01,606,1,296.72,6.39,0,0
1,22.58705,92.50738,329.40,0.63,0.72,2018-04-01,606,1,299.01,7.35,0,0
2,22.58846,92.51312,337.59,0.63,0.72,2018-04-01,606,1,299.01,6.89,0,0
3,22.50259,92.55136,330.26,0.63,0.72,2018-04-01,606,1,299.59,8.80,0,0
4,22.50408,92.55746,346.15,0.63,0.72,2018-04-01,606,1,298.87,10.10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
5089534,18.68441,73.03601,307.54,0.33,0.55,2026-05-31,2123,1,295.24,1.66,1,2
5089535,18.68378,73.03909,307.61,0.33,0.55,2026-05-31,2123,1,295.08,1.66,1,2
5089536,18.67941,73.03488,319.23,0.33,0.55,2026-05-31,2123,1,294.86,1.66,1,0
5089537,18.42220,73.94517,303.59,0.38,0.59,2026-05-31,2123,1,291.45,0.53,1,0
5089538,15.65745,73.98907,301.50,0.44,0.62,2026-05-31,2124,1,267.11,1.12,1,2