In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('~/mission_sih/mission_sih/data/land_use_data.csv')

In [3]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 17650701 entries, 0 to 17650700
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   year       int64
 1   land_type  str
 2   latitude   float64
 3   longitude  float64
dtypes: float64(2), int64(1), str(1)
memory usage: 538.7 MB

In [4]:
df2 = pd.read_csv("~/mission_sih/mission_sih/data/nasa_data_cleaned.csv")

In [5]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5089539 entries, 0 to 5089538
Data columns (total 12 columns):
 #   Column      Dtype
---  ------      -----
 0   latitude    float64
 1   longitude   float64
 2   brightness  float64
 3   scan        float64
 4   track       float64
 5   acq_date    str
 6   acq_time    int64
 7   confidence  int64
 8   bright_t31  float64
 9   frp         float64
 10  daynight    int64
 11  type        int64
dtypes: float64(7), int64(4), str(1)
memory usage: 466.0 MB

In [7]:
df1.head(3)

   year    land_type   latitude  longitude
0  2018  Agriculture  37.072196  74.712681
1  2018  Agriculture  37.062195  74.682680
2  2018  Agriculture  37.052194  74.682680

In [19]:
df2.head(3)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,confidence,bright_t31,frp,daynight,type
0,23.04102,92.52061,336.69,0.62,0.71,2018-04-01,606,1,296.72,6.39,0,0
1,22.58705,92.50738,329.40,0.63,0.72,2018-04-01,606,1,299.01,7.35,0,0
2,22.58846,92.51312,337.59,0.63,0.72,2018-04-01,606,1,299.01,6.89,0,0

In [20]:
df3 = df2[df2["latitude"] == 23]

In [21]:
df3.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,confidence,bright_t31,frp,daynight,type
460973,23.0,92.91400,356.47,0.59,0.70,2019-03-19,607,0,290.91,37.49,0,0
536536,23.0,75.88287,354.33,0.38,0.36,2019-04-03,806,1,327.52,24.81,0,0
1089308,23.0,78.08293,343.45,0.43,0.38,2020-04-22,748,0,309.16,9.22,0,0